

import { Poppins } from "next/font/google";
import "./globals.css";
import styles from "@/styles/home.module.css";
import SessionProvider  from '@/auth/session-provider';
const poppins = Poppins({ subsets: ["latin"], weight: ['400', '700'] });

export const metadata = {
  title: "Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={(poppins.className, styles.body)} >
      <SessionProvider>
      {children}
      </SessionProvider>
      
      
      </body>
    </html>
  );
}
